/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ehacks.mod.util.diffgui;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import net.minecraft.client.resources.I18n;
import net.minecraft.potion.Potion;

/**
 *
 * @author radioegor146
 */
public class PotionsRegistry extends javax.swing.JFrame {

    /**
     * Creates new form DiffFrame
     */
    public PotionsRegistry() {
        initComponents();
        ArrayList<PotionsRegistry.PotionInfo> potionInfos = new ArrayList();
        for (Potion potion : Potion.potionTypes) {
            if (potion == null) continue;
            potionInfos.add(new PotionInfo(potion));
        }
        int maxIdLength = 2;
        int maxClassNameLength = 5;
        int maxNameLength = 4;
        for (PotionInfo potion : potionInfos) {
            maxIdLength = Math.max(maxIdLength, potion.id.length());
            maxClassNameLength = Math.max(maxClassNameLength, potion.className.length());
            maxNameLength = Math.max(maxNameLength, potion.name.length());
        }
        int margin = 3;
        maxIdLength += margin;
        maxClassNameLength += margin;
        maxNameLength += margin;
        int overallLength = maxIdLength + maxClassNameLength + maxNameLength;
        ((DefaultListModel)this.potionsList.getModel()).clear();
        StringBuilder infoString = new StringBuilder();
        infoString.append("ID");
        for (int i = 0; i < maxIdLength - 2; i++)
            infoString.append(' ');
        infoString.append("Name");
        for (int i = 0; i < maxNameLength - 4; i++)
            infoString.append(' ');
        infoString.append("Class");
        for (int i = 0; i < maxClassNameLength - 5; i++)
            infoString.append(' ');
        ((DefaultListModel)this.potionsList.getModel()).addElement(infoString.toString());
        StringBuilder delimString = new StringBuilder();
        for (int i = 0; i < overallLength; i++)
            delimString.append("-");
        ((DefaultListModel)this.potionsList.getModel()).addElement(delimString.toString());
        for (PotionInfo potion : potionInfos) {
            StringBuilder potionString = new StringBuilder();
            potionString.append(potion.id);
            for (int i = 0; i < maxIdLength - potion.id.length(); i++)
                potionString.append(' ');
            potionString.append(potion.name);
            for (int i = 0; i < maxNameLength - potion.name.length(); i++)
                potionString.append(' ');
            potionString.append(potion.className);
            for (int i = 0; i < maxClassNameLength - potion.className.length(); i++)
                potionString.append(' ');
            ((DefaultListModel)this.potionsList.getModel()).addElement(potionString.toString()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        potionsScrollPane = new javax.swing.JScrollPane();
        potionsList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Potion effect registry");

        potionsList.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        potionsList.setModel(new javax.swing.DefaultListModel());
        potionsScrollPane.setViewportView(potionsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(potionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(potionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    
    public class PotionInfo {
        public String className;
        public String name;
        public String id;
        
        public PotionInfo(Potion potion) {
            className = potion.getClass().getName();
            name =  I18n.format(potion.getName());
            id = String.valueOf(potion.id);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JList<String> potionsList;
    private javax.swing.JScrollPane potionsScrollPane;
    // End of variables declaration                   
}
