/* Generated By:JJTree: Do not edit this line. BSHFormalComment.java */
package ehacks.bsh;

public class BSHFormalComment extends SimpleNode {

    public String text;

    public BSHFormalComment(int id) {
        super(id);
    }

}
